name: reviewdog
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  reviewdog-pr:
    if: github.event_name == 'pull_request'
    name: reviewdog on Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - uses: actions/checkout@v2

      # https://github.com/actions/cache/blob/master/examples.md#go---modules
      - name: Cache Go Modules
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Go Modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Install linters
        run: '( cd linters && go get golang.org/x/lint/golint )'

      - name: Setup reviewdog
        # uses: reviewdog/action-setup@v1
        run: |
          go install ./cmd/reviewdog

      - name: Run reviewdog (github-pr-check)
        continue-on-error: true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -reporter=github-pr-check -runners=golint,govet -fail-on-error

      - name: Run reviewdog (github-pr-review with tee)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Remove Go Problem Matchers [1] as it reports duplicate results with
          # reviewdog.
          # [1]: https://github.com/actions/toolkit/blob/master/docs/commands.md#problem-matchers
          echo "::remove-matcher owner=go::"
          golint ./... | reviewdog -f=golint -name=golint-pr-review -reporter=github-pr-review -tee

      - name: Run reviewdog with sub-dir (github-pr-review)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./_testdata/ && golint ./... | reviewdog -f=golint -name=golint-pr-review-subdir -reporter=github-pr-review -tee

      - name: Run reviewdog with sub-dir (local+fail-on-error)
        run: |
          echo 'var LocalTest = 14' >> ./_testdata/golint.go
          cd ./_testdata/ && golint ./... | reviewdog -f=golint -diff="git diff" -fail-on-error || EXIT_CODE=$?
          git reset --hard @
          test "${EXIT_CODE}" = 1

      - name: Run reviewdog (github-pr-check with fail-on-error)
        continue-on-error: true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./_testdata/ && golint ./... | reviewdog -f=golint -name=golint-pr-check-fail-on-error -reporter=github-pr-check -fail-on-error

      - name: Run reviewdog (github-pr-check with -filter-mode=file)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          golint | reviewdog -f=golint -name=golint-pr-check-filter-mode-file -reporter=github-pr-check -filter-mode=file -level=warning

      - name: Run reviewdog (github-pr-review -filter-mode=nofilter)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./_testdata/ && golint ./... | reviewdog -f=golint -name=golint-pr-review-nofilter -reporter=github-pr-review -filter-mode=nofilter -fail-on-error || EXIT_CODE=$?
          test "${EXIT_CODE}" = 1

      - name: Unexpected failure (github-pr-review)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./_testdata/ && reviewdog -conf=reviewdog_error.yml \
            -reporter=github-pr-review || EXIT_CODE=$?
          test "${EXIT_CODE}" = 1
      - name: Unexpected failure (github-check)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./_testdata/ && reviewdog -conf=reviewdog_error.yml \
            -reporter=github-check || EXIT_CODE=$?
          test "${EXIT_CODE}" = 1
      - name: Unexpected failure (local)
        run: |
          cd ./_testdata/ && reviewdog -conf=reviewdog_error.yml \
            -reporter=local -diff='git diff master' || EXIT_CODE=$?
          test "${EXIT_CODE}" = 1
      - name: Suggestion (rdjsonl)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat ./_testdata/suggestions.json | \
            reviewdog -name="suggestion-test" -f=rdjsonl -reporter=github-pr-review

      - name: Custom rdjsonl test (github-pr-review)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat ./_testdata/custom_rdjson.json | \
            reviewdog -name="custom-rdjson" -f=rdjson -reporter=github-pr-review

      - name: gofmt -s with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gofmt -s -d . | \
            reviewdog -name="gofmt" -f=diff -f.diff.strip=0 -reporter=github-pr-review

  golangci-lint:
    if: github.event_name == 'pull_request'
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--enable-all --exclude-use-default=false -D wsl -D testpackage"
          level: "warning"
          reporter: github-pr-check

  staticcheck:
    if: github.event_name == 'pull_request'
    name: runner / staticcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-staticcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true
          # workdir: ./_testdata/

  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
          reporter: github-check

  languagetool:
    name: runner / languagetool
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-languagetool@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info
          patterns: |
            **/*.md
            !**/testdata/**

  shellcheck:
    if: github.event_name == 'pull_request'
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
